<html>

<head>
    <title>MyCMS</title>

    <script src="js/angular.min.js"></script>
    <script src="js/truncate.js"></script>
    <script src="js/app.js"></script>

    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
</head>


<body ng-app="mycms">

<header>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav header-menu">
            <li><a href="">Home</a></li>
            <li><a href="#/about">About</a></li>
        </ul>
    </div>
</header>

<div class="content" ng-controller="MainCtrl">

    <ul class="post-list list-unstyled">
        <li ng-repeat="post in posts">
            <div class="post-card">
                <h3 class="post-title"><?php echo Phalcon\Tag::linkTo('posts/post/{{post.id}}','{{post.title}}'); ?></h3>
                <p class="post-content">{{ post.content | words:40 }}</p>
            </div>
        </li>
    </ul>

</div>

</body>

</html>