<html>

<head>
    <title>MyCMS</title>

    <script src="js/angular.min.js"></script>
    <script src="js/app.js"></script>
</head>


<body ng-app="mycms">

<div class="content" ng-controller="MainCtrl">
    {{hello}}
    <ul>
        <li ng-repeat="post in posts">
            <?php echo Phalcon\Tag::linkTo('posts/post/{{post.id}}','<h3>{{post.title}}</h3>'); ?>
            {{post.content}}
        </li>
    </ul>
</div>

</body>

</html>